### ISSUE TITLE
是否去干预模板的需要？

### ISSUE THREAD

**Issue by xuexb** [xuexb/node-combo#3]

**Comment by xuexb** [comment]
比如动态的替换`src`标签和时间缀问题

**Comment by nimoc** [comment]
需求具体点？

**Comment by xuexb** [comment]
@nimojs 这个话题是由今天我参加美丽说同学分享的他们的开发模式，大致是这样的：

他们有套他们的开发模式，在开发完成后，需要编译模板，编译过程会根据配置替换模板里的`link`,`script`路径，并根据`js`的文件生成`md5`的版本号，并生成依赖地图配置，然后页面在访问时首先走`cdn`，如果不存在则请求`nginx`并代理到`jsserver`（`nodejs`写的静态服务），然后`jsserver`根据请求（如~pro:index/header+pro:account/login+pro:index/banner+pro:index/main.js?v=4d38f41944）的`url`生成每个文件的路径，并根据依赖地图读取每个文件的依赖，并加载，然后生成数据返回浏览器。

干预模板的好处：
1. 可以做到每个文件都是一个版本号，因为是`md5`的，这样就可以避免在修改一个文件而修改全局时间缀带来的问题
2. 可以根据配置生成`url`并写入模板

干预模板的不帅地方：
1. 每次修改文件都需要编译模板，略繁琐
2. 开发人员必须非常熟悉这套模式，本地也需要相关的支持，比如装相关的工具包

但可能当团队大的时候需要那些编译，比如百度的`fis`，但我认为团队小的时候还是敏捷开发吧，特别是我现在一个人。。。

跟定位有关吧，感觉还是想把`node-combo`做成服务端的合并/处理工具，不干预任何模板上的东西，至于清缓存的问题，如果不涉及到`cdn`可以使用后期写的`缓存管理`功能清除，但如果依赖`cdn`那么就要看项目了，且她较适合于解决中，小团队模块化开发打包合并的问题。

ps: 经测试美丽说的静态资源在第一次加载的时候50K左右的大概会在6-9s时间

> [点这里看美丽说项目](http://pro.meilishuo.com/)

**Comment by nimoc** [comment]
了解
我看过 https://github.com/fouber/blog/issues/6 后也一直在考虑 md5 戳的问题

目前我想做的与 fis 一致，都是后端读取 json 根据 json 中文件名对应的版本号去输出路径。

本地开发直接是访问 source.js ，线上读取json 后返回 source.sdh2ds2d.js 。

每次前端本地发布到测试机时候都需要构建一次（检索所有文件生成对应的MD5版本）

可以看看我在这个帖子的描述 http://div.io/topic/930 

> 送个 div.io 社区的注册邀请码 MLVL-PMFR-RMGC-JT2U （这个社区的文章质量有保证）

我觉得应该抛弃 ?v=23233 的方式，直接使用md5文件名解决缓存问题。

我工作中遇到一个场景必须有 md5文件后缀的支持，否则满足不了需求。

**Comment by xuexb** [comment]
但如果想使用`md5`版本的方式就得干预模板了额

**Comment by nimoc** [comment]
恩是的，我们是直接在后端开发框架的模板支持读取 json 然后根据 key(a.js) 得到 value(a.sd7dh2d.js)

必须要“干预模板”

**但是我觉得这件事不应该是 node-combo 去做，而是后端开发环境去做**

前端静态资源服务器应该提供 combo 等简单 的服务器，前端静态资源服务器不应该变得复杂
