### ISSUE TITLE
global 是否应该在本地实现？

### ISSUE THREAD

**Issue by nimoc** [xuexb/node-combo#4]
别名加载

例子：

```
alias: {
    'global': 'src/??seajs/sea,seajs/sea-style,seajs/sea-config,lib/dialog/base'
},
```

demo.com/??global 就相当于 demo.com/src/??seajs/sea,seajs/sea-style,seajs/sea-config,lib/dialog/base

如果global也在服务器端实现的话，多个项目的前端资源文件放在同一个服务器，alias 会非常多. 

alias是否就交由本地 loader 库配置去实现？

**Comment by nimoc** [comment]
这与 node-combo 的定位有关系。

---

1、 只是 combo服务器，

---

2、 还是在线自动打包服务器。
类似本地开发 comonjs 代码。发布到线上访问时自动转换为 cmd代码

**Comment by xuexb** [comment]
起初我想的别名是解决一个连接过长在页面很难看的问题。。。跟代码无关，其实就是`url`的简写

**Comment by nimoc** [comment]
恩，我觉得这个 url 缩写方便了，但是会增加维护的复杂度。因为我有可能有个代码就是 global.js

或者多人维护这个 server 时会出现很多的 alias
